<?php
    require_once    "../config/config.php";
     require_once    "../config/auth.php";
$token = $_GET['access_token'];
$unique_id = md5(uniqid());

// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, 'https://api-m.paypal.com/v1/catalogs/products');
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_POST, 1);
curl_setopt($ch, CURLOPT_POSTFIELDS, "{\n  \"name\": \"Video Streaming Service\",\n  \"description\": \"A video streaming service\",\n  \"type\": \"SERVICE\",\n  \"category\": \"SOFTWARE\",\n  \"image_url\": \"https://pastortibipeters.online/assets/images/desktop/logo.png\",\n  \"home_url\": \"https://pastortibipeters.online\"\n}");

$headers = array();
$headers[] = 'Content-Type: application/json';
$headers[] = 'Authorization: Bearer '.rawurlencode($token);
$headers[] = 'Paypal-Request-Id: '.rawurlencode($unique_id);
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = curl_exec($ch);
$err = curl_error($ch);
curl_close($ch);
if ($err) {
    # code...
    echo 'Error:'.$err;
}else {
    $response = json_decode($result);
    //var_dump($response);
     $ProductID = $response->id;
//    var_dump($ProductID);

   if ($ProductID) {
        # code...
      header("Location: createplan.php?ProductID=".$ProductID."&access_token=".$token);
       exit();
   }
}

?>