<?php
require_once    "../config/config.php";
require_once    "../config/auth.php";
$subscriptionID = $_GET['subscriptionID'];
$token = $_GET['access_token'];
if ($subscriptionID =="" OR $token == "") {
    header("Location: javascript://history.go(-1)");
}

?>

<?php

// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, 'https://api-m.paypal.com/vi/billing/subscriptions/'.rawurlencode($subscriptionID));
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');


$headers = array();
$headers[] = 'Content-Type: application/json';
$headers[] = 'Authorization: Bearer '.rawurlencode($token);
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = curl_exec($ch);
$err = curl_error($ch);
curl_close($ch);
if ($err) {
    # code...
    echo 'Error:'.$err;
} else {
  $user_name=$_SESSION["username"];
  $user_email=$_SESSION["email"];
  $duration_subscription= $_SESSION['subscription_duration'];

//   date_default_timezone_set('Africa/Lagos');

// $today = new DateTime('today');
// echo 'Today is ', $today->format('F d, Y'), '.<br>', PHP_EOL;
// //$_SESSION['today']=$today;
//     // Today is August 28, 2013 12:00am.<br>
// $expiration = new DateTime('today +90 days');
// echo 'Expires ', $expiration->format('F d, Y'), '.<br>', PHP_EOL;
    // Expires November 13, 2014 12:01am.<br>
$uid=$_SESSION['uid'];
$today=date("d-M-Y");
$expiration_date="Active";
$_SESSION['expiration_date']=$expiration_date;
$media_id=$_SESSION['media_id'];
  $db->query("UPDATE users SET duration_subcription='$duration_subscription',date_subscribed='$today',expiration_date='$expiration_date' WHERE uid='$uid' ");
  $db->query("UPDATE audio_subscription SET subscription_access='Paid' WHERE user_id='$uid' ");
    $_SESSION['msg']="Your subscription would last for $duration, which would expire on $expiration.";
    $_SESSION['color']="success";
  header("location:../user/audio_subscription.php?media_id=");



}

?>